### ISSUE TITLE
the 400 responses

### ISSUE THREAD

**Issue by JWDobken** [mikeckennedy/restful-services-in-pyramid#2]
Is there a good reason why you are using the responses like:

    return Response(status=400, msg)

instead of using [pyramid's httpexceptions](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/httpexceptions.html#module-pyramid.httpexceptions):

    return HTTPBadRequest(msg)

**Comment by mikeckennedy** [comment]
Hi JW. Not really. 

I didn't think of digging into the specific response classes vs. just setting the status code when all that is really being communicated is the status code.

I definitely see the value in these specialized classes for things like 302 redirects where headers are set and whatnot. But mostly I just didn't have it on my radar for this one.

That said, I think it's totally fine to use `HTTPBadRequest` here.

Best,
Michael
